// frontend/app/react/src/components/layout/TopNavbar.tsx
'use client';

import React, {useState, useEffect} from 'react';
import {Menu, Tabs} from 'antd';
import {XIcon} from '@/plugins/xicon';

import type {siteservicev1_Navigation, siteservicev1_NavigationItem} from '@/api/generated/app/service/v1';
import {useNavigationStore} from '@/store/slices/navigation/hooks';
import {useLanguageStore} from '@/store/core/language/hooks';

import type {TopNavBarTabItem} from './types';
import TopNavbarTab from './TopNavbarTab';

import styles from './TopNavbar.module.css';

export interface TopNavbarItem {
    key: string;
    label: string;
    icon?: string;
    children?: TopNavbarItem[];
}

interface TopNavbarProps {
    items?: TopNavbarItem[];
    onClick?: (key: number) => void;
}

// 模拟左侧和右侧的 Tab 列表（实际应该从 store 获取）
const leftTabList: TopNavBarTabItem[] = [];
const rightTabList: TopNavBarTabItem[] = [];

export default function TopNavbar({onClick}: TopNavbarProps) {
    const navigationStore = useNavigationStore();
    const languageStore = useLanguageStore();
    const [navigationItems, setNavigationItems] = useState<siteservicev1_NavigationItem[]>([]);
    const [activeOverlay, setActiveOverlay] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(true);

    // 将数据转换为 Ant Design Menu 所需的格式
    const getMenuOptions = (navItems: siteservicev1_NavigationItem[]) => {
        return navItems.map(item => ({
            key: item.id,
            label: item.title,
            icon: item.icon ? <XIcon name={`carbon:${item.icon}`} size={22}/> : undefined,
            children: item.children && item.children.length > 0
                ? item.children.map((child: siteservicev1_NavigationItem) => ({
                    key: child.id,
                    label: child.title,
                    icon: child.icon ? <XIcon name={`carbon:${child.icon}`} size={18}/> : undefined,
                }))
                : undefined,
        }));
    };

    // 隐藏悬浮层
    const hideOverlay = () => {
        setActiveOverlay(null);
    };

    // 加载导航数据
    useEffect(() => {
        async function loadNavigation() {
            try {
                setIsLoading(true);

                // 调用 API 获取所有导航数据
                const res = await navigationStore.listNavigation(
                    {page: 1, pageSize: 10}
                ) as unknown as {items: siteservicev1_Navigation[]; total: number};

                if (res.items && res.items.length > 0) {
                    res.items.forEach((nav, index) => {
                        console.log(`[${index}] location: ${nav.location}, isActive: ${nav.isActive}, items count: ${nav.items?.length}`);
                        console.log(`[${index}] items:`, nav.items);
                    });

                    // 在前端过滤出 HEADER 位置且激活的导航
                    const headerNav = res.items.find(nav =>
                        nav.location === 'HEADER' && nav.isActive === true
                    );

                    if (headerNav && headerNav.items && headerNav.items.length > 0) {
                        setNavigationItems(headerNav.items);
                    }
                }
            } catch (error) {
                console.error('❌ 加载导航失败:', error);
            } finally {
                setIsLoading(false);
            }
        }

        loadNavigation();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [languageStore.language.locale]); // 当语言变化时重新加载导航数据

    // TODO: 后续添加语言切换监听，自动重新加载导航数据

    // 处理导航点击
    const handleNavigate = (item: siteservicev1_NavigationItem) => {
        if (item.isOpenNewTab) {
            window.open(item.url, '_blank');
        } else {
            if (item.url != null) {
                // TODO: 使用 router.push 时保留 history state
                window.location.href = item.url;
            }
        }
    };

    const menuItems = getMenuOptions(navigationItems);

    console.log('=== Menu 渲染 ===');
    console.log('navigationItems:', navigationItems);
    console.log('menuItems:', menuItems);
    console.log('isLoading:', isLoading);

    return (
        <div className={styles.navbarWrapper}>
            <div className={styles.navbarLeft}>
                {/* 左侧导航菜单 */}
                {isLoading ? (
                    <div className={styles.loadingState}>
                        Loading navigation...
                    </div>
                ) : navigationItems.length > 0 ? (
                    <Menu
                        mode="horizontal"
                        className={styles.navbarMenu}
                        items={menuItems}
                        onClick={({key}) => {
                            const item = navigationStore.findNavItem(navigationItems, Number(key));
                            if (item) handleNavigate(item);
                            onClick?.(Number(key));
                        }}
                    />
                ) : (
                    <div className={styles.loadingState}>
                        No navigation items
                    </div>
                )}

                {/* 原有的 Tabs */}
                {leftTabList.length > 0 && (
                    <Tabs
                        activeKey={activeOverlay || undefined}
                        type="card"
                        trigger="hover"
                        animated
                        onTabClick={(key) => setActiveOverlay(key)}
                        onMouseLeave={hideOverlay}
                        items={leftTabList.map(item => ({
                            key: item.key,
                            label: <TopNavbarTab data={item}/>,
                            children: (
                                <div className={styles.overlayMask}>
                                    <div className={styles.overlay}>
                                        <item.component/>
                                    </div>
                                </div>
                            ),
                        }))}
                    />
                )}
            </div>

            <div className={styles.navbarRight}>
                {rightTabList.length > 0 && (
                    <Tabs
                        activeKey={activeOverlay || undefined}
                        type="card"
                        trigger="hover"
                        animated
                        onTabClick={(key) => setActiveOverlay(key)}
                        onMouseLeave={hideOverlay}
                        items={rightTabList.map(item => ({
                            key: item.key,
                            label: <TopNavbarTab data={item}/>,
                            children: (
                                <div className={styles.overlayMask}>
                                    <div className={styles.overlay}>
                                        <item.component/>
                                    </div>
                                </div>
                            ),
                        }))}
                    />
                )}
            </div>
        </div>
    );
}

// frontend/app/vue3/src/components/Navbar/TopNavbar.vue
<script setup lang="ts">
import {h, ref, onMounted} from 'vue';
import {useRouter} from 'vue-router';
import {useNavbarStore, useNavigationStore} from "@/stores";
import {XIcon} from '@/plugins/xicon';
import type {TopNavBarTabItem} from "./types";
import TopNavbarTab from './TopNavbarTab.vue';

const router = useRouter();
const navbarStore = useNavbarStore();
const navigationStore = useNavigationStore();

const leftTabList: TopNavBarTabItem[] = []
const rightTabList: TopNavBarTabItem[] = [];
const navigationItems = ref<any[]>([]);

/**
 * 隐藏所有的悬浮层
 */
function hideOverlay() {
  navbarStore.setActiveOverlay(null);
}

/**
 * 加载导航数据
 */
async function loadNavigation() {
  try {
    const res = await navigationStore.listNavigation(
      {page: 1, pageSize: 10},
      {location: 'header', isActive: true}
    );
    if (res.items && res.items.length > 0) {
      navigationItems.value = res.items[0].items || [];
    }
  } catch (error) {
    console.error('Load navigation failed:', error);
  }
}

/**
 * 处理导航点击
 */
function handleNavigate(item: any) {
  if (item.isOpenNewTab) {
    window.open(item.url, '_blank');
  } else {
    router.push(item.url);
  }
}


onMounted(() => {
  loadNavigation();
});
</script>

<template>
  <n-space justify="space-between">
    <n-space align="center" :size="8">
      <!-- 左侧导航菜单 -->
      <n-menu
        v-if="navigationItems.length > 0"
        mode="horizontal"
        :options="navigationItems.map(item => ({
          key: item.id,
          label: item.title,
          icon: item.icon ? () => h(XIcon, { name: `carbon:${item.icon}`, size: 18 }) : undefined,
          children: item.children && item.children.length > 0 ? item.children.map((child: any) => ({
            key: child.id,
            label: child.title,
            icon: child.icon ? () => h(XIcon, { name: `carbon:${child.icon}`, size: 16 }) : undefined,
          })) : undefined,
        }))"
        @update:value="(key: number) => {
          const findItem = (items: any[]): any => {
            for (const item of items) {
              if (item.id === key) return item;
              if (item.children) {
                const found = findItem(item.children);
                if (found) return found;
              }
            }
            return null;
          };
          const item = findItem(navigationItems);
          if (item) handleNavigate(item);
        }"
      />

      <!-- 原有的 Tabs -->
      <n-tabs
        v-model:value="navbarStore.activeOverlay"
        type="bar"
        trigger="hover"
        animated
        @mouseleave="hideOverlay"
      >
        <n-tab-pane
          v-for="item in leftTabList" :key="item.key" :name="item.key"
          :tab="() => h(TopNavbarTab, { data: item })"
        >
          <div class="overlay-mask">
            <div class="overlay">
              <component :is="item.component" class="stick-content"/>
            </div>
          </div>
        </n-tab-pane>
      </n-tabs>
    </n-space>

    <n-space align="center">
      <n-tabs
        v-model:value="navbarStore.activeOverlay"
        type="bar"
        trigger="hover"
        animated
        @mouseleave="hideOverlay"
      >
        <n-tab-pane
          v-for="item in rightTabList" :key="item.key" :name="item.key"
          :tab="() => h(TopNavbarTab, { data: item })"
        >
          <div class="overlay-mask">
            <div class="overlay">
              <transition name="fade" mode="out-in">
                <component :is="item.component" class="stick-content"/>
              </transition>
            </div>
          </div>
        </n-tab-pane>
      </n-tabs>
    </n-space>
  </n-space>
</template>

<style scoped lang="less">
@import '@/styles/app.less';

.overlay {
  background-color: var(--color-surface);
  border-top: 1px solid var(--color-border);
  z-index: 9999;
  pointer-events: auto;
  min-height: 15vh;
  color: var(--color-text-primary);
}

.overlay-mask {
  position: fixed;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.3);
  backdrop-filter: blur(4px);
  z-index: 9998;
  pointer-events: none;
}

// Menu 样式
:deep(.n-menu) {
  background: transparent;
  color: var(--color-text-primary);
}

:deep(.n-menu-item) {
  color: var(--color-text-primary) !important;
  padding: 8px 16px;
  border-radius: var(--radius-sm);
  transition: all 0.2s;
}

:deep(.n-menu-item:hover) {
  color: var(--color-brand) !important;
  background: rgba(102, 126, 234, 0.05);
}

:deep(.n-menu-item--selected) {
  color: var(--color-brand) !important;
  background: rgba(102, 126, 234, 0.1);
}

:deep(.n-menu-item-content) {
  display: flex;
  align-items: center;
  gap: 8px;
}

:deep(.n-menu-item-content__icon) {
  display: flex;
  align-items: center;
}

// Submenu 样式
:deep(.n-submenu) {
  color: var(--color-text-primary);
}

:deep(.n-submenu-children) {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

// Tabs 样式
:deep(.n-tabs) {
  color: var(--color-text-primary);
}

// Tab 项样式
:deep(.n-tabs-tab) {
  color: var(--color-text-primary) !important;
  padding: 8px 16px;
}

:deep(.n-tabs-tab:hover) {
  color: var(--color-brand) !important;
  background: rgba(102, 126, 234, 0.05);
}

// 激活的 Tab
:deep(.n-tabs-tab--active) {
  color: var(--color-brand) !important;
}

// Tab 下划线
:deep(.n-tabs-bar) {
  background-color: var(--color-brand);
}

// Tab 内容
:deep(.n-tabs-tab__label) {
  color: inherit;
}

// Space 组件
:deep(.n-space) {
  color: var(--color-text-primary);
}

.default-enter-active {
  transition: all 0.3s ease-in;
}

.default-leave-active {
  transition: all 0.3s ease-out;
}

.default-enter,
.default-leave-to {
  max-height: 0;
}
</style>
