// frontend/app/taro/src/pages/login/components/EmailLoginPage.tsx
import {useState} from 'react';
import {useTranslation} from 'react-i18next';

import {useAuthenticationStore} from "@/store/slices/authentication/hooks";

import '../index.scss';

export default function EmailLoginPage() {
  const {t} = useTranslation('authentication');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [rememberMe, setRememberMe] = useState(false);

  const authenticationStore = useAuthenticationStore();

  const handleLogin = async () => {
    if (!email || !password) {
      return;
    }
    console.log('登录信息:', {email, password, rememberMe});

    await authenticationStore.login({
      email: email,
      password: password,
    });
  };

  const handleForgotPassword = () => {
    console.log('忘记密码');
  };

  return (
    <div className="login-form">
      <div className="form-group">
        <label htmlFor="login-email">{t('register.email')}</label>
        <input
          id="login-email"
          type="email"
          className="input-field"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          placeholder={t('login.placeholder_email')}
          autoComplete="email"
        />
      </div>

      <div className="form-group">
        <label htmlFor="login-password-email">{t('login.password')}</label>
        <input
          id="login-password-email"
          type="password"
          className="input-field"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          placeholder={t('login.placeholder_password')}
          autoComplete="current-password"
          onKeyDown={(e) => e.key === 'Enter' && handleLogin()}
        />
      </div>

      <div className="form-options">
        <label className="checkbox-label">
          <input
            type="checkbox"
            checked={rememberMe}
            onChange={(e) => setRememberMe(e.target.checked)}
          />
          <span>{t('login.remember_me')}</span>
        </label>
        <button className="text-btn" onClick={handleForgotPassword}>
          {t('login.forgot_password')}
        </button>
      </div>

      <button className="login-button" onClick={handleLogin}>
        {t('login.login')}
      </button>
    </div>
  );
}

// frontend/app/vue3/src/pages/login/components/EmailLoginPage.vue
<script setup lang="ts">
import {ref} from 'vue';
import {$t} from '@/locales';

const email = ref('');
const password = ref('');
const rememberMe = ref(false);

function handleLogin() {
  // TODO: 实现登录逻辑
  console.log('登录信息：', {
    email: email.value,
    password: password.value,
    rememberMe: rememberMe.value,
  });
}

function handleForgotPassword() {
  // TODO: 跳转到忘记密码页面
  console.log('忘记密码');
}
</script>

<template>
  <div class="login-form">
    <div class="form-group">
      <label>{{ $t('authentication.register.email') }}</label>
      <n-input
        v-model:value="email"
        :placeholder="$t('authentication.login.placeholder_email')"
        type="text"
        clearable
      />
    </div>
    <div class="form-group">
      <label>{{ $t('authentication.login.password') }}</label>
      <n-input
        v-model:value="password"
        type="password"
        :placeholder="$t('authentication.login.placeholder_password')"
        clearable
        show-password-on="click"
        @keyup.enter="handleLogin"
      />
    </div>
    <div class="form-options">
      <n-checkbox v-model:checked="rememberMe">{{ $t('authentication.login.remember_me') }}</n-checkbox>
      <n-button text type="primary" @click="handleForgotPassword">
        {{ $t('authentication.login.forgot_password') }}
      </n-button>
    </div>
    <n-button type="primary" block size="large" class="login-button" @click="handleLogin">
      {{ $t('authentication.login.login') }}
    </n-button>
  </div>
</template>

<style scoped lang="less">
.login-form {
  display: flex;
  flex-direction: column;
}

.form-group {
  margin-bottom: 1.5rem;

  label {
    display: block;
    font-weight: 500;
    margin-bottom: 0.5rem;
    font-size: 0.95rem;
    color: var(--color-text-primary);
  }
}

.form-options {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1.5rem;
  font-size: 0.95rem;
}

.login-button {
  font-weight: 600;
  height: 44px;
  margin-bottom: 1.5rem;
}
</style>
