// frontend/app/taro/src/pages/register/components/PhoneRegisterPage.tsx
import {useState, useEffect} from 'react';
import {useTranslation} from 'react-i18next';

import '../register.scss';

export default function PhoneRegisterPage() {
  const {t} = useTranslation();

  const [phone, setPhone] = useState('');
  const [verificationCode, setVerificationCode] = useState('');
  const [codeSent, setCodeSent] = useState(false);
  const [codeCountdown, setCodeCountdown] = useState(0);

  useEffect(() => {
    let codeTimer: number | null = null;

    if (codeSent && codeCountdown > 0) {
      codeTimer = window.setInterval(() => {
        setCodeCountdown((prev) => {
          if (prev <= 1) {
            setCodeSent(false);
            return 0;
          }
          return prev - 1;
        });
      }, 1000);
    }

    return () => {
      if (codeTimer !== null) {
        clearInterval(codeTimer);
      }
    };
  }, [codeSent, codeCountdown]);

  /**
   * 发送验证码
   */
  const handleButtonSendVerifyCode = () => {
    if (!phone) {
      return;
    }

    setCodeSent(true);
    setCodeCountdown(60);
  };

  /**
   * 登录或者注册
   */
  const handleButtonRegisterOrLogin = () => {
    if (!phone || !verificationCode) {
      return;
    }
    console.log('手机号注册/登录:', {phone, verificationCode});
  };

  return (
    <div className='register-form'>
      {/* Phone Number Group */}
      <div className='form-group'>
        <label htmlFor='register-phone-number'>
          {t('authentication.register.phone')}
        </label>
        <input
          id='register-phone-number'
          type='text'
          value={phone}
          onChange={(e) => setPhone(e.target.value)}
          placeholder={t('authentication.register.input_phone')}
          autoComplete='tel'
          className='input-field'
        />
      </div>

      {/* Verification Code Group */}
      <div className='form-group'>
        <label htmlFor='register-phone-code'>
          {t('authentication.register.code')}
        </label>
        <div className='code-input-row'>
          <input
            id='register-phone-code'
            type='text'
            value={verificationCode}
            onChange={(e) => setVerificationCode(e.target.value)}
            placeholder={t('authentication.register.input_code')}
            maxLength={6}
            autoComplete='one-time-code'
            className='input-field'
          />
          <button
            type='button'
            disabled={codeSent}
            className={`send-code-btn ${codeSent ? 'disabled' : ''}`}
            onClick={handleButtonSendVerifyCode}
          >
            {codeSent ? `${codeCountdown}s` : t('authentication.register.send_code')}
          </button>
        </div>
      </div>

      {/* Register Button */}
      <button
        type='button'
        className='register-button'
        onClick={handleButtonRegisterOrLogin}
      >
        {t('authentication.register.register_or_login')}
      </button>
    </div>
  );
}

// frontend/app/vue3/src/pages/register/components/PhoneRegisterPage.vue
<script setup lang="ts">
import {ref} from "vue";
import {$t} from '@/locales';

const phone = ref('');
const verificationCode = ref('');
const codeSent = ref(false);
const codeCountdown = ref(0);

/**
 * 发送验证码
 */
function handleButtonSendVerifyCode() {
  if (!phone.value) {
    // TODO: 显示错误提示
    return;
  }

  codeSent.value = true;
  codeCountdown.value = 60;

  // TODO: 实现发送验证码逻辑

  // 倒计时
  const timer = setInterval(() => {
    codeCountdown.value--;
    if (codeCountdown.value <= 0) {
      clearInterval(timer);
      codeSent.value = false;
    }
  }, 1000);
}

/**
 * 登录或者注册
 */
function handleButtonRegisterOrLogin() {
  if (!phone.value || !verificationCode.value) {
    // TODO: 显示错误提示
    return;
  }

  // TODO: 实现注册或登录逻辑
}
</script>

<template>
  <div class="register-form">
    <!-- Phone Number Group -->
    <div class="form-group">
      <label>{{ $t('authentication.register.phone') }}</label>
      <n-input
        v-model:value="phone"
        :placeholder="$t('authentication.register.input_phone')"
        clearable
        type="text"
      />
    </div>

    <!-- Verification Code Group -->
    <div class="form-group">
      <label>{{ $t('authentication.register.code') }}</label>
      <div class="code-input-row">
        <n-input
          v-model:value="verificationCode"
          :placeholder="$t('authentication.register.input_code')"
          maxlength="6"
          type="text"
        />
        <n-button
          :disabled="codeSent"
          :type="codeSent ? 'default' : 'primary'"
          class="send-code-btn"
          @click="handleButtonSendVerifyCode"
        >
          {{ codeSent ? `${codeCountdown}s` : $t('authentication.register.send_code') }}
        </n-button>
      </div>
    </div>

    <!-- Register Button -->
    <n-button
      type="primary"
      block
      size="large"
      class="register-button"
      @click="handleButtonRegisterOrLogin"
    >
      {{ $t('authentication.register.register_or_login') }}
    </n-button>
  </div>
</template>

<style scoped lang="less">
.register-form {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;

  label {
    display: block;
    font-weight: 500;
    font-size: 0.95rem;
    color: var(--color-text-primary);
  }
}

.code-input-row {
  display: flex;
  gap: 0.75rem;
  align-items: center;

  :deep(.n-input) {
    flex: 1;
  }

  .send-code-btn {
    flex-shrink: 0;
    width: 120px;
    height: 40px;
    font-size: 0.9rem;
    white-space: nowrap;
  }
}

.register-button {
  font-weight: 600;
  height: 44px;
  margin-top: 0.5rem;
}
</style>
