// frontend/app/react/src/app/[locale]/register/page.tsx
'use client';

import {useState, useMemo} from 'react';
import {useTranslations} from 'next-intl';

import '../../globals.css'; // 导入全局 CSS，确保 CSS 变量可用
import styles from './register.module.css';

import AccountRegisterPage from './components/AccountRegisterPage';
import EmailRegisterPage from './components/EmailRegisterPage';
import PhoneRegisterPage from './components/PhoneRegisterPage';
import OtherRegisterPage from './components/OtherRegisterPage';
import ControlPanel from '@/components/layout/ControlPanel';

export default function RegisterPage() {
    const t = useTranslations('authentication');
    const [activeTab, setActiveTab] = useState<'account' | 'email' | 'phone' | 'other'>('account');

    // 语言选项
    const languageOptions = useMemo(() => [
        {key: 'zh-CN', label: '中文'},
        {key: 'en-US', label: 'English'}
    ], []);

    // 登录
    const handleLoginClick = () => {
        window.location.href = '/login';
    };

    // 返回首页
    const handleBackHome = () => {
        window.location.href = '/';
    };

    // 服务条款
    const handleTermsClick = () => {
        window.location.href = '/terms';
    };

    // 隐私政策
    const handlePrivacyClick = () => {
        window.location.href = '/privacy';
    };

    return (
        <div className={styles['register-page']}>
            {/* 顶部控制按钮 */}
            <ControlPanel/>

            {/* 左侧品牌区 */}
            <div className={styles['register-left']}>
                <div className={styles.brand}>
                    <img src="/logo.png" alt={t('login.logo_alt')} className={styles['brand-logo']}/>
                    <h1 className={styles['brand-title']}>{t('login.brand_title')}</h1>
                    <p className={styles['brand-subtitle']}>{t('login.brand_subtitle')}</p>
                </div>

                <div className={styles['benefits-list']}>
                    <div className={styles['benefit-item']}>
                        <span>✓</span>
                        <span>{t('login.feature_projects')}</span>
                    </div>
                    <div className={styles['benefit-item']}>
                        <span>✓</span>
                        <span>{t('login.feature_isolation')}</span>
                    </div>
                    <div className={styles['benefit-item']}>
                        <span>✓</span>
                        <span>{t('login.feature_permissions')}</span>
                    </div>
                    <div className={styles['benefit-item']}>
                        <span>✓</span>
                        <span>{t('login.feature_analytics')}</span>
                    </div>
                </div>
            </div>

            {/* 右侧注册卡片 */}
            <div className={styles['register-right']}>
                <div className={styles['register-card']}>
                    <div className={styles['card-header']}>
                        <h2>{t('register.title')}</h2>
                        <p>{t('register.register_with')}</p>
                    </div>

                    {/* Tab 切换 */}
                    <div className={styles['register-tabs']}>
                        <button
                            className={`${styles.tab} ${activeTab === 'account' ? styles.active : ''}`}
                            onClick={() => setActiveTab('account')}
                        >
                            {t('login.tab_account')}
                        </button>
                        <button
                            className={`${styles.tab} ${activeTab === 'email' ? styles.active : ''}`}
                            onClick={() => setActiveTab('email')}
                        >
                            {t('login.tab_email')}
                        </button>
                        <button
                            className={`${styles.tab} ${activeTab === 'phone' ? styles.active : ''}`}
                            onClick={() => setActiveTab('phone')}
                        >
                            {t('login.tab_phone')}
                        </button>
                        <button
                            className={`${styles.tab} ${activeTab === 'other' ? styles.active : ''}`}
                            onClick={() => setActiveTab('other')}
                        >
                            {t('login.tab_other')}
                        </button>
                    </div>

                    {/* 注册表单内容 */}
                    <div className={styles['register-content']}>
                        {activeTab === 'account' && <AccountRegisterPage/>}
                        {activeTab === 'email' && <EmailRegisterPage/>}
                        {activeTab === 'phone' && <PhoneRegisterPage/>}
                        {activeTab === 'other' && <OtherRegisterPage/>}
                    </div>

                    {/* 登录链接 */}
                    <div className={styles['login-section']}>
                        <p>
                            {t('register.already_have_account')}
                            <button className={styles['text-btn']} onClick={handleLoginClick}>
                                {t('register.login_now')}
                            </button>
                        </p>
                    </div>

                    {/* 返回首页 */}
                    <div className={styles['back-home']}>
                        <button className={styles['text-btn']} onClick={handleBackHome}>
                            ← {t('login.back_home')}
                        </button>
                    </div>

                    {/* 服务条款 */}
                    <div className={styles.terms}>
                        <small>
                            {t('login.terms_prefix')}
                            <button className={styles['text-btn']} onClick={handleTermsClick}>
                                {t('login.terms_of_service')}
                            </button>
                            {t('login.terms_and')}
                            <button className={styles['text-btn']} onClick={handlePrivacyClick}>
                                {t('login.privacy_policy')}
                            </button>
                        </small>
                    </div>
                </div>
            </div>
        </div>
    );
}

// frontend/app/vue3/src/pages/register/index.vue
<script setup lang="ts">
import {ref} from "vue";
import {definePage} from "unplugin-vue-router/runtime";
import {useRouter} from 'vue-router'
import {$t} from '@/locales';

import AccountRegisterPage from "./components/AccountRegisterPage.vue";
import EmailRegisterPage from "./components/EmailRegisterPage.vue";
import PhoneRegisterPage from "./components/PhoneRegisterPage.vue";
import OtherRegisterPage from "./components/OtherRegisterPage.vue";

definePage({
  name: 'register',
  meta: {
    level: 1,
    hideLayout: true, // 隐藏全局 Header 和 Footer
    forceLight: true, // 强制使用亮色主题
  },
})

const router = useRouter()
const activeTab = ref('account');

const handleLoginClick = () => {
  router.push('/login')
}

const handleBackHome = () => {
  router.push('/')
}
</script>

<template>
  <div class="register-page">
    <!-- Left Side - Brand -->
    <div class="register-left">
      <div class="brand">
        <img src="/logo.png" :alt="$t('authentication.login.logo_alt')" class="brand-logo" />
        <h1 class="brand-title">{{ $t('authentication.login.brand_title') }}</h1>
        <p class="brand-subtitle">{{ $t('authentication.login.brand_subtitle') }}</p>
      </div>

      <div class="benefits-list">
        <div class="benefit-item">
          <span>✓</span>
          <span>{{ $t('authentication.login.feature_projects') }}</span>
        </div>
        <div class="benefit-item">
          <span>✓</span>
          <span>{{ $t('authentication.login.feature_isolation') }}</span>
        </div>
        <div class="benefit-item">
          <span>✓</span>
          <span>{{ $t('authentication.login.feature_permissions') }}</span>
        </div>
        <div class="benefit-item">
          <span>✓</span>
          <span>{{ $t('authentication.login.feature_analytics') }}</span>
        </div>
      </div>
    </div>

    <!-- Right Side - Register Form -->
    <div class="register-right">
      <n-card :bordered="false" class="register-card">
        <template #header>
          <div class="card-header">
            <h2>{{ $t('authentication.register.title') }}</h2>
            <p>{{ $t('authentication.register.register_with') }}</p>
          </div>
        </template>

        <n-tabs v-model:value="activeTab" type="segment" animated class="register-tabs">
          <n-tab-pane name="account" :tab="$t('authentication.login.tab_account')">
            <AccountRegisterPage/>
          </n-tab-pane>

          <n-tab-pane name="email" :tab="$t('authentication.login.tab_email')">
            <EmailRegisterPage/>
          </n-tab-pane>

          <n-tab-pane name="phone" :tab="$t('authentication.login.tab_phone')">
            <PhoneRegisterPage/>
          </n-tab-pane>

          <n-tab-pane name="other" :tab="$t('authentication.login.tab_other')">
            <OtherRegisterPage/>
          </n-tab-pane>
        </n-tabs>

        <!-- Login Link -->
        <div class="login-section">
          <p>{{ $t('authentication.register.already_have_account') }}
            <n-button text type="primary" @click="handleLoginClick">
              {{ $t('authentication.register.login_now') }}
            </n-button>
          </p>
        </div>

        <div class="back-home">
          <n-button text type="primary" @click="handleBackHome">
            ← {{ $t('authentication.login.back_home') }}
          </n-button>
        </div>

        <!-- Terms -->
        <div class="terms">
          <small>
            {{ $t('authentication.login.terms_prefix') }}
            <n-button text type="primary">{{ $t('authentication.login.terms_of_service') }}</n-button>
            {{ $t('authentication.login.terms_and') }}
            <n-button text type="primary">{{ $t('authentication.login.privacy_policy') }}</n-button>
          </small>
        </div>
      </n-card>
    </div>
  </div>
</template>

<style scoped lang="less">
.register-page {
  display: flex;
  min-height: 100vh;
  background: var(--color-bg);

  .register-left {
    flex: 1;
    background: linear-gradient(135deg, var(--color-brand) 0%, var(--color-brand-accent) 100%);
    color: #fff;
    padding: 4rem 2rem;
    display: flex;
    flex-direction: column;
    justify-content: space-between;

    .brand {
      text-align: center;
      margin-bottom: 3rem;

      .brand-logo {
        width: 80px;
        height: 80px;
        margin-bottom: 1rem;
      }

      .brand-title {
        font-size: 2.5rem;
        font-weight: 700;
        margin-bottom: 0.5rem;
      }

      .brand-subtitle {
        font-size: 1.1rem;
        opacity: 0.92;
      }
    }

    .benefits-list {
      display: flex;
      flex-direction: column;
      gap: 1rem;

      .benefit-item {
        display: flex;
        align-items: center;
        gap: 1rem;
        padding: 1rem 0;
        font-size: 1.05rem;
      }
    }
  }

  .register-right {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 2rem;

    .register-card {
      width: 100%;
      max-width: 420px;
      border: 1px solid var(--color-border);
      border-radius: var(--radius-md);

      .card-header {
        text-align: center;
        margin-bottom: 1.5rem;

        h2 {
          font-size: 1.75rem;
          margin-bottom: 0.5rem;
          color: var(--color-text-primary);
        }

        p {
          color: var(--color-text-secondary);
          font-size: 0.95rem;
        }
      }
    }
  }
}

.register-tabs {
  margin-bottom: 1.5rem;
}

.login-section {
  text-align: center;
  padding: 1.5rem 0;
  border-top: 1px solid var(--color-border);
  border-bottom: 1px solid var(--color-border);

  p {
    margin: 0;
    font-size: 0.95rem;
    color: var(--color-text-secondary);
  }
}

.back-home {
  text-align: center;
  padding: 1rem 0;

  :deep(.n-button) {
    font-size: 0.9rem;
  }
}

.terms {
  text-align: center;
  margin-top: 1rem;
  color: var(--color-text-secondary);
  line-height: 1.6;

  small {
    font-size: 0.85rem;
  }
}

@media (max-width: 1024px) {
  .register-page {
    flex-direction: column;

    .register-left {
      padding: 2rem;
      min-height: 200px;
      justify-content: flex-start;
    }

    .register-right {
      flex: 1;
      background: var(--color-surface);

      .register-card {
        max-width: 100%;
      }
    }
  }
}
</style>
