// frontend/app/vue3/src/pages/category/index.vue
<script setup lang="ts">
import {definePage} from 'unplugin-vue-router/runtime'
import {ref, onMounted} from 'vue'

import {useCategoryStore} from '@/stores'
import {$t} from '@/locales'
import {useLanguageChangeEffect} from '@/hooks/useLanguageChangeEffect';
import {CategoryTree} from '@/components/CategoryTree'
import type {contentservicev1_Category} from "@/api/generated/app/service/v1";

definePage({
  name: 'category-list',
  meta: {
    title: 'Categories',
    level: 2,
  },
})

const categoryStore = useCategoryStore()

const loading = ref(false)
const categories = ref<contentservicev1_Category[]>([])

async function loadCategories() {
  loading.value = true
  try {
    const res = await categoryStore.listCategory(
      undefined,
      {status: 'CATEGORY_STATUS_ACTIVE'},
      'id,status,sort_order,icon,code,post_count,direct_post_count,parent_id,created_at,children,translations.id,translations.category_id,translations.name,translations.language_code,translations.description,translations.thumbnail,translations.cover_image',
      ['-sortOrder']
    )
    categories.value = res.items || []
  } catch (error) {
    console.error('Load categories failed:', error)
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  loadCategories()
})

// 监听语言切换，自动重新加载数据
useLanguageChangeEffect(loadCategories, {
  immediate: false,    // 已经在 onMounted 中加载，不需要立即执行
  autoCleanup: true,   // 组件卸载时自动取消订阅
});
</script>

<template>
  <div class="category-page">
    <!-- Hero Section -->
    <div class="hero-section">
      <div class="hero-content">
        <h1>{{ $t('page.categories.categories') }}</h1>
        <p>{{ $t('page.categories.browse_all') }}</p>
      </div>
    </div>

    <!-- Content Section -->
    <div class="page-container">
      <!-- Loading Skeleton -->
      <div v-if="loading" class="categories-loading">
        <div v-for="i in 6" :key="i" class="category-loading-card">
          <n-skeleton height="160px"/>
        </div>
      </div>

      <!-- Loaded Content -->
      <div v-else>
        <CategoryTree
          v-if="categories.length > 0"
          :categories="categories"
        />

        <n-empty
          v-else
          :description="$t('page.categories.no_categories')"
          style="margin: 80px 0;"
        >
          <template #icon>
            <span class="i-carbon:folder-blank" style="font-size: 64px;"/>
          </template>
        </n-empty>
      </div>
    </div>
  </div>
</template>

<style scoped lang="less">
.category-page {
  min-height: 100vh;
  background: var(--color-bg);
}

// Hero Section
.hero-section {
  background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #a855f7 100%);
  padding: 3rem 2rem;
  margin-bottom: 40px;
  position: relative;
  overflow: hidden;
  min-height: 350px;
  height: auto;
  display: flex;
  align-items: center;
  justify-content: center;
  text-align: center;
  color: white;

  // 背景装饰：渐变和网格
  &::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: radial-gradient(ellipse at 20% 50%, rgba(100, 200, 255, 0.15) 0%, transparent 50%),
    radial-gradient(ellipse at 80% 80%, rgba(200, 100, 255, 0.12) 0%, transparent 50%),
    linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #a855f7 100%);
    animation: gradientShift 15s ease-in-out infinite;
    z-index: 0;
  }

  // 网格背景
  &::after {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-image: linear-gradient(rgba(255, 255, 255, 0.05) 1px, transparent 1px),
    linear-gradient(90deg, rgba(255, 255, 255, 0.05) 1px, transparent 1px);
    background-size: 50px 50px;
    animation: gridMove 20s linear infinite;
    opacity: 0.6;
    z-index: 1;
  }

  .hero-content {
    max-width: 1200px;
    margin: 0 auto;
    text-align: center;
    position: relative;
    z-index: 2;
    animation: fadeInUp 0.8s ease-out;

    h1 {
      font-size: 48px;
      font-weight: 800;
      margin: 0 0 16px 0;
      color: #ffffff;
      letter-spacing: -1px;
      line-height: 1.1;

      // 添加发光效果
      background: linear-gradient(135deg,
      #ffffff 0%,
      #f0f0ff 25%,
      #e0e0ff 50%,
      #f0f0ff 75%,
      #ffffff 100%);
      background-size: 200% auto;
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-clip: text;

      text-shadow: 0 0 40px rgba(255, 255, 255, 0.9),
      0 0 80px rgba(var(--color-primary-purple-rgb), 0.7),
      0 0 120px rgba(99, 102, 241, 0.5),
      0 6px 24px rgba(0, 0, 0, 0.5),
      0 3px 12px rgba(0, 0, 0, 0.4);

      filter: drop-shadow(0 0 30px rgba(var(--color-primary-purple-rgb), 0.6)) drop-shadow(0 0 60px rgba(99, 102, 241, 0.4)) drop-shadow(0 5px 15px rgba(0, 0, 0, 0.3));

      animation-name: slideDown, glowPulseTitle, gradientShine;
      animation-duration: 0.8s, 3s, 6s;
      animation-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1), ease-in-out, linear;
      animation-iteration-count: 1, infinite, infinite;
      animation-delay: 0s, 0.5s, 0s;
    }

    p {
      font-size: 20px;
      color: rgba(255, 255, 255, 0.95);
      margin: 0;
      font-weight: 500;
      text-shadow: 0 2px 10px rgba(0, 0, 0, 0.25);
      animation: fadeInUp 0.8s ease-out 0.2s both;
    }
  }
}

// Page Container
.page-container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 32px 80px;
}

// Loading State
.categories-loading {
  display: flex;
  flex-direction: column;
  gap: 24px;

  .category-loading-card {
    background: var(--color-surface);
    border-radius: 16px;
    overflow: hidden;
  }
}

// Responsive Design
@media (max-width: 1024px) {
  .hero-section {
    padding: 3rem 1.5rem 2.5rem;
    min-height: 300px;
    margin-bottom: 36px;

    .hero-content {
      h1 {
        font-size: 40px;
        letter-spacing: -0.8px;
        margin-bottom: 14px;
      }

      p {
        font-size: 18px;
      }
    }
  }

  .page-container {
    padding: 0 24px 60px;
  }
}

@media (max-width: 768px) {
  .hero-section {
    padding: 2.5rem 1.5rem 2rem;
    min-height: 280px;
    margin-bottom: 32px;

    &::after {
      background-size: 30px 30px;
    }

    .hero-content {
      h1 {
        font-size: 34px;
        margin-bottom: 12px;
        letter-spacing: -0.6px;
        line-height: 1.2;
      }

      p {
        font-size: 17px;
        line-height: 1.5;
      }
    }
  }

  .page-container {
    padding: 0 20px 50px;
  }
}

@media (max-width: 640px) {
  .hero-section {
    padding: 2rem 1rem;
    min-height: 240px;
    margin-bottom: 28px;

    &::after {
      background-size: 25px 25px;
    }

    .hero-content {
      h1 {
        font-size: 28px;
        margin-bottom: 10px;
        letter-spacing: -0.4px;
      }

      p {
        font-size: 16px;
      }
    }
  }

  .page-container {
    padding: 0 16px 40px;
  }
}

@media (max-width: 480px) {
  .hero-section {
    padding: 1.75rem 1rem 1.5rem;
    min-height: 220px;
    margin-bottom: 24px;

    &::before {
      animation: gradientShift 20s ease-in-out infinite;
    }

    &::after {
      background-size: 20px 20px;
      animation: gridMove 30s linear infinite;
    }

    .hero-content {
      padding: 0;

      h1 {
        font-size: 24px;
        margin-bottom: 8px;
        letter-spacing: -0.3px;
        line-height: 1.3;

        // 移动端简化发光效果
        text-shadow: 0 0 30px rgba(255, 255, 255, 0.8),
        0 0 60px rgba(var(--color-primary-purple-rgb), 0.6),
        0 4px 16px rgba(0, 0, 0, 0.4);

        filter: drop-shadow(0 0 20px rgba(var(--color-primary-purple-rgb), 0.5)) drop-shadow(0 3px 10px rgba(0, 0, 0, 0.3));
      }

      p {
        font-size: 14px;
        line-height: 1.5;
      }
    }
  }

  .page-container {
    padding: 0 12px 32px;
  }
}

// 动画关键帧定义
@keyframes slideDown {
  from {
    opacity: 0;
    transform: translateY(-30px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes gradientShift {
  0%, 100% {
    background: radial-gradient(ellipse at 20% 50%, rgba(100, 200, 255, 0.15) 0%, transparent 50%),
    radial-gradient(ellipse at 80% 80%, rgba(200, 100, 255, 0.12) 0%, transparent 50%),
    linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #a855f7 100%);
  }
  50% {
    background: radial-gradient(ellipse at 80% 50%, rgba(100, 200, 255, 0.15) 0%, transparent 50%),
    radial-gradient(ellipse at 20% 80%, rgba(200, 100, 255, 0.12) 0%, transparent 50%),
    linear-gradient(135deg, #8b5cf6 0%, #a855f7 50%, #6366f1 100%);
  }
}

@keyframes gridMove {
  0% {
    transform: translate(0, 0);
  }
  100% {
    transform: translate(50px, 50px);
  }
}

// Dark Mode Enhancements
html.dark {
  .hero-section {
    background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #a855f7 100%);
    box-shadow: 0 20px 60px rgba(99, 102, 241, 0.3);

    &::before {
      opacity: 1;
    }

    .hero-content {
      h1 {
        background: linear-gradient(135deg,
        #ffffff 0%,
        #f5f5ff 25%,
        #ebebff 50%,
        #f5f5ff 75%,
        #ffffff 100%);
        background-size: 200% auto;
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        background-clip: text;

        text-shadow: 0 0 50px rgba(255, 255, 255, 1),
        0 0 100px rgba(var(--color-primary-purple-rgb), 0.8),
        0 0 150px rgba(99, 102, 241, 0.6),
        0 8px 30px rgba(0, 0, 0, 0.6),
        0 4px 15px rgba(0, 0, 0, 0.4);

        filter: drop-shadow(0 0 35px rgba(var(--color-primary-purple-rgb), 0.7)) drop-shadow(0 0 70px rgba(99, 102, 241, 0.5)) drop-shadow(0 6px 20px rgba(0, 0, 0, 0.4));
      }
    }
  }
}
</style>

// frontend/app/react/src/app/[locale]/category/page.tsx
'use client';

import {useState, useEffect} from 'react';
import {useTranslations} from 'next-intl';
import {Skeleton, Empty} from 'antd';

import {useCategoryStore} from '@/store/slices/category/hooks';
import CategoryTree from '@/components/category/CategoryTree';

import {contentservicev1_Category, contentservicev1_ListCategoryResponse} from "@/api/generated/app/service/v1";
import {useI18nRouter} from "@/i18n/helpers";

import '../../globals.css'; // 导入全局 CSS，确保 CSS 变量可用
import styles from './page.module.css';

export default function CategoryListPage() {
    const t = useTranslations('page');
    const router = useI18nRouter();
    const categoryStore = useCategoryStore();

    const [loading, setLoading] = useState(false);
    const [categories, setCategories] = useState<contentservicev1_Category[]>([]);

    async function loadCategories() {
        setLoading(true);
        try {
            const res = (await categoryStore.listCategory({
                // @ts-expect-error - listCategory 参数类型推断问题
                paging: undefined,
                formValues: {status: 'CATEGORY_STATUS_ACTIVE'},
                fieldMask: 'id,status,sort_order,icon,code,post_count,direct_post_count,parent_id,created_at,children,translations.id,translations.category_id,translations.name,translations.language_code,translations.description,translations.thumbnail,translations.cover_image',
                orderBy: ['-sortOrder']
            })) as unknown as contentservicev1_ListCategoryResponse;
            setCategories(res.items || []);
        } catch (error) {
            console.error('Load categories failed:', error);
        } finally {
            setLoading(false);
        }
    }

    useEffect(() => {
        loadCategories();
    }, []);

    const handleCategoryClick = (id: number) => {
        router.push(`/category/${id}`);
    };

    return (
        <div className={styles['category-page']}>
            {/* Hero Section */}
            <div className={styles['hero-section']}>
                <div className={styles['hero-content']}>
                    <h1>{t('categories.categories')}</h1>
                    <p>{t('categories.browse_all')}</p>
                </div>
            </div>

            {/* Content Section */}
            <div className={styles['page-container']}>
                {/* Loading Skeleton */}
                {loading ? (
                    <div className={styles['categories-loading']}>
                        {[...Array(6)].map((_, i) => (
                            <div key={i} className={styles['category-loading-card']}>
                                <Skeleton height={160} active/>
                            </div>
                        ))}
                    </div>
                ) : (
                    <>
                        {categories.length > 0 ? (
                            <CategoryTree
                                categories={categories}
                                onCategoryClick={handleCategoryClick}
                            />
                        ) : (
                            <Empty
                                description={t('categories.no_categories')}
                                style={{margin: '80px 0'}}
                                image={<span className="i-carbon:folder-blank" style={{fontSize: '64px'}}/>}
                            />
                        )}
                    </>
                )}
            </div>
        </div>
    );
}
