// frontend/app/taro/src/pages/disclaimer/index.tsx
import {useTranslation} from 'react-i18next';
import {View, Text} from '@tarojs/components';

import './disclaimer.scss';

export default function DisclaimerPage() {
  const {t} = useTranslation();

  return (
    <View className='info-page'>
      {/* Hero Section */}
      <View className='hero'>
        <View className='hero-content'>
          <Text className='hero-title'>{t('page.legal.disclaimer.title')}</Text>
          <Text className='hero-subtitle'>{t('page.legal.disclaimer.description')}</Text>
        </View>
      </View>

      {/* Content Section */}
      <View className='info-card'>
        <View className='list'>
          <Text>{t('page.legal.disclaimer.item_1')}</Text>
          <Text>{t('page.legal.disclaimer.item_2')}</Text>
          <Text>{t('page.legal.disclaimer.item_3')}</Text>
        </View>
      </View>
    </View>
  );
}

// frontend/app/vue3/src/pages/disclaimer/index.vue
<script setup lang="ts">
import {definePage} from 'unplugin-vue-router/runtime'
import {$t} from '@/locales'

definePage({
  name: 'disclaimer',
  meta: {
    level: 2,
  },
})
</script>

<template>
  <div class="info-page">
    <div class="info-card stick-content section-shell">
      <h1 class="title">{{ $t('ui.button.non_responsibility') }}</h1>
      <p class="desc">{{ $t('page.legal.disclaimer.description') }}</p>
      <ul class="list">
        <li>{{ $t('page.legal.disclaimer.item_1') }}</li>
        <li>{{ $t('page.legal.disclaimer.item_2') }}</li>
        <li>{{ $t('page.legal.disclaimer.item_3') }}</li>
      </ul>
    </div>
  </div>
</template>

<style scoped lang="less">
.info-page {
  min-height: calc(100vh - var(--layout-header-height));
  background: var(--color-bg);
  padding: 24px 0;
}

.info-card {
  padding: 28px;
}

.title {
  margin: 0 0 12px;
  color: var(--color-text-primary);
}

.desc {
  margin: 0 0 12px;
  color: var(--color-text-secondary);
}

.list {
  margin: 0;
  padding-left: 18px;
  color: var(--color-text-primary);
  line-height: 1.8;
}
</style>
